# -*- coding: utf-8 -*-
"""Plotting Weather Patterns Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18g8drUw8G2E8K0oMB15YRFzIUfC2Gu1f

# Assignment 2

Before working on this assignment please read these instructions fully. In the submission area, you will notice that you can click the link to **Preview the Grading** for each step of the assignment. This is the criteria that will be used for peer grading. Please familiarize yourself with the criteria before beginning the assignment.

An NOAA dataset has been stored in the file `data/C2A2_data/BinnedCsvs_d400/fb441e62df2d58994928907a91895ec62c2c42e6cd075c2700843b89.csv`. This is the dataset to use for this assignment. Note: The data for this assignment comes from a subset of The National Centers for Environmental Information (NCEI) [Daily Global Historical Climatology Network](https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt) (GHCN-Daily). The GHCN-Daily is comprised of daily climate records from thousands of land surface stations across the globe.

Each row in the assignment datafile corresponds to a single observation.

The following variables are provided to you:

* **id** : station identification code
* **date** : date in YYYY-MM-DD format (e.g. 2012-01-24 = January 24, 2012)
* **element** : indicator of element type
    * TMAX : Maximum temperature (tenths of degrees C)
    * TMIN : Minimum temperature (tenths of degrees C)
* **value** : data value for element (tenths of degrees C)

For this assignment, you must:

1. Read the documentation and familiarize yourself with the dataset, then write some python code which returns a line graph of the record high and record low temperatures by day of the year over the period 2005-2014. The area between the record high and record low temperatures for each day should be shaded.
2. Overlay a scatter of the 2015 data for any points (highs and lows) for which the ten year record (2005-2014) record high or record low was broken in 2015.
3. Watch out for leap days (i.e. February 29th), it is reasonable to remove these points from the dataset for the purpose of this visualization.
4. Make the visual nice! Leverage principles from the first module in this course when developing your solution. Consider issues such as legends, labels, and chart junk.

The data you have been given is near **Ann Arbor, Michigan, United States**, and the stations the data comes from are shown on the map below.
"""

import matplotlib.pyplot as plt
import mplleaflet
import pandas as pd
import numpy as np

def leaflet_plot_stations(binsize, hashid):

    df = pd.read_csv('data/C2A2_data/BinSize_d{}.csv'.format(binsize))

    station_locations_by_hash = df[df['hash'] == hashid]

    lons = station_locations_by_hash['LONGITUDE'].tolist()
    lats = station_locations_by_hash['LATITUDE'].tolist()

    plt.figure(figsize=(8,8))

    plt.scatter(lons, lats, c='r', alpha=0.7, s=200)

    return mplleaflet.display()

leaflet_plot_stations(400,'fb441e62df2d58994928907a91895ec62c2c42e6cd075c2700843b89')

df = pd.read_csv('data/C2A2_data/BinnedCsvs_d25/391a2922ad597ba080f4b99dea6d62842562d64845ef5df1a384561e.csv')
df.head()

""" 1 write some python code which returns a line graph 
of the record high and record low temperatures by day of the year over the period 2005-2014. The area between the record high 
and record low temperatures for each day should be shaded.
"""

#remove month and day of year
df['Year'] = df['Date'].apply(lambda x: x[:4])
df['Date2'] = df['Date'].apply(lambda x: x[-5:])

#remove leap days
df = df[df['Date2'] != '02-29']

#Date in 2005-2014
data_not15 = df[~(df['Year'] == '2015')]
#Date in 2015
data_15 = df[df['Year'] == '2015']

data_not15.head()

#Min Max for 2005-2014
max_not15 = data_not15.groupby('Date2').agg({'Data_Value':np.max})
min_not15 = data_not15.groupby('Date2').agg({'Data_Value':np.min})
max_not15.head()

# Commented out IPython magic to ensure Python compatibility.
#line graph of the record high and record low temperatures by day of the year 
#over the period 2005-2014. The area between the record high and record low 
#temperatures for each day should be shaded.
# %matplotlib inline
plt.figure()
plt.figure(figsize=(16,10))
plt.plot(max_not15.values,'-o',min_not15.values,'o')

plt.xlabel('Day',fontsize=20)
plt.ylabel('Temperature',fontsize=20)
plt.title('Record high and record low temperatures (2005-2014)',fontsize=25)

plt.gca().fill_between(range(len(max_not15)), 
                       np.array(max_not15.values.reshape(len(max_not15.values),)), 
                       np.array(min_not15.values.reshape(len(min_not15.values),)), 
                       facecolor='blue', 
                       alpha=0.20)

#Min Max for 2015
max_15 = data_15.groupby('Date2').agg({'Data_Value':np.max})
min_15 = data_15.groupby('Date2').agg({'Data_Value':np.min})

all_max = pd.merge(max_not15.reset_index(), max_15.reset_index(), left_index=True, on = 'Date2')
all_min = pd.merge(min_not15.reset_index(), min_15.reset_index(), left_index=True, on = 'Date2')
all_max.head()

#2015 broke record of 2005-2014
break_max = all_max[all_max['Data_Value_y'] > all_max['Data_Value_x']]
break_min = all_min[all_min['Data_Value_y'] < all_min['Data_Value_x']]
break_max.head()

"""2. Overlay a scatter of the 2015 data for any points (highs and lows) for which the ten year record (2005-2014) record high or record low was broken in 2015."""



plt.figure()
plt.figure(figsize=(16,10))

plt.plot(max_not15.values, label ='Record High')
plt.plot(min_not15.values, c='#848482',label ='Record Low')

plt.xlabel('Day',fontsize=20)
plt.ylabel('Temperature',fontsize=20)
plt.title('Ten Year Record (2005-2014) Was Broken in 2015', fontsize=25)

plt.scatter(break_max.index.tolist(), break_max['Data_Value_y'].values, c = 'green', label = "Broken High in 2015")
plt.scatter(break_min.index.tolist(), break_min['Data_Value_y'].values, c = 'red', label = "Broken Low in 2015")

plt.gca().fill_between(range(len(max_not15)), 
                       np.array(max_not15.values.reshape(len(max_not15.values),)), 
                       np.array(min_not15.values.reshape(len(min_not15.values),)), 
                       facecolor='gray', 
                       alpha=0.2)

plt.gca().axis([-5, 370, -450, 550])
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.legend(loc = 8, fontsize=18, frameon = False)

a = [0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]
b = [i+15 for i in a]
Month_name = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
plt.xticks(b, Month_name)

plt.show()